spring:
  application:
    name: telegrotion
  datasource:
    url: ${DB.URL:jdbc:postgresql://localhost:5432/telegrotion}
    username: ${DB.USERNAME:postgres}
    password: ${DB.PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: postgresql
#    redis:
#      host: ${REDIS_HOST:ec2-54-154-92-250.eu-west-1.compute.amazonaws.com}
#      port: ${REDIS_PORT:13100}
#      password: ${REDIS_PASSWORD:p6341f559bf45b1c649fb323f0594776490553898c49dfdcf6fe0afa0b53d443a}
#      url: rediss://:p6341f559bf45b1c649fb323f0594776490553898c49dfdcf6fe0afa0b53d443a@ec2-54-154-92-250.eu-west-1.compute.amazonaws.com:13100

heroku:
  redis:
    host: ${REDIS_HOST:ec2-54-154-92-250.eu-west-1.compute.amazonaws.com}
    port: ${REDIS_PORT:13100}
    password: ${REDIS_PASSWORD:p6341f559bf45b1c649fb323f0594776490553898c49dfdcf6fe0afa0b53d443a}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          socket: DEBUG
#        messaging: DEBUG