spring:
  application:
    name: telegrotion
  datasource:
    url: ${DB.URL:jdbc:postgresql://localhost:5432/telegrotion}
    username: ${DB.USERNAME:postgres}
    password: ${DB.PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: postgresql

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: DEBUG