spring:
  application:
    name: telegrotion
  datasource:
    url: ${DB.URL:jdbc:postgresql://localhost:5432/fizzly}
    username: ${DB.USERNAME:alexander}
    password: ${DB.PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: postgresql
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    multipart:
      enabled: true
heroku:
  redis:
    host: ${REDIS_HOST:ec2-54-154-92-250.eu-west-1.compute.amazonaws.com}
    port: ${REDIS_PORT:13100}
    password: ${REDIS_PASSWORD:p6341f559bf45b1c649fb323f0594776490553898c49dfdcf6fe0afa0b53d443a}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          socket: DEBUG
#        messaging: DEBUG