version: '3.8'
services:
  app:
    image: alexanderrybak/fizzly-app:version-1
    ports:
      - "8080:8080"
    environment:
      DB.URL: jdbc:postgresql://db:5432/mydb
      DB.USERNAME: postgres
      DB.PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: